services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak
    restart: unless-stopped
    command: 
      - start 
      - --db=postgres
      - --hostname=keycloak.our-galaxy.space
      - --proxy-headers=xforwarded
      - --health-enabled=true
      - --metrics-enabled=true
      - --http-enabled=true
    env_file:
      - .env 
    volumes:
      - ./themes:/opt/keycloak/themes
    environment:
      KC_HTTP_ENABLED: "true"
      #
      KC_HTTP_MANAGEMENT_ENABLED: "true"
      KC_HTTP_MANAGEMENT_PORT: "9000"
      # Отключаем авторизацию к метрикам для Prometheus
      KC_METRICS_AUTH: "false"
      # Блок БД
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL} 
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      # Блок админа
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8081:8080"
    networks:
      - monitoring

networks:
  monitoring:
    external: true
